# _config.yml
title: yuan_blog | Developer  # 您的网站标题
description: >- 
  This is my personal portfolio and blog website.
  # 网站描述
baseurl: "" # 如果您的仓库名是 `WrzY23.github.io`，这里就留空
url: "https://WrzY23.github.io" # 您的网站网址
# theme: minima # 注释掉这行，因为我们使用自定义布局和样式

# 插件
plugins:
  - jekyll-feed
  - jekyll-sass-converter

# 站内导航
header_pages:
  - index.md
  - ideas.md
  - photography.md
  - tech_notes.md
  - writings.md
  - about.md